#!/bin/bash

# Create project folder and subfolders
mkdir -p p2p-chat-example/src/main/java/com/example/p2p/chat
mkdir -p p2p-chat-example/src/main/resources
mkdir -p p2p-chat-example/src/test/java/com/example/p2p/chat

# Create pom.xml file
cat > p2p-chat-example/pom.xml <<EOF
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
             <modelVersion>4.0.0</modelVersion>

                 <groupId>com.example</groupId>
                     <artifactId>p2p-chat-example</artifactId>
                         <version>0.0.1-SNAPSHOT</version>
                             <packaging>jar</packaging>

                                 <name>P2P Chat Example</name>
                                     <description>P2P chat example project</description>

                                         <parent>
                                                 <groupId>org.springframework.boot</groupId>
                                                         <artifactId>spring-boot-starter-parent</artifactId>
                                                                 <version>2.4.3</version>
                                                                         <relativePath/> <!-- lookup parent from repository -->
                                                                             </parent>

                                                                                 <properties>
                                                                                         <java.version>1.8</java.version>
                                                                                             </properties>

                                                                                                 <dependencies>
                                                                                                         <dependency>
                                                                                                                     <groupId>org.springframework.boot</groupId>
                                                                                                                                 <artifactId>spring-boot-starter-web</artifactId>
                                                                                                                                         </dependency>
                                                                                                                                                 <dependency>
                                                                                                                                                             <groupId>org.springframework.boot</groupId>
                                                                                                                                                                         <artifactId>spring-boot-starter-data-jpa</artifactId>
                                                                                                                                                                                 </dependency>
                                                                                                                                                                                         <dependency>
                                                                                                                                                                                                     <groupId>org.springframework.boot</groupId>
                                                                                                                                                                                                                 <artifactId>spring-boot-starter-security</artifactId>
                                                                                                                                                                                                                         </dependency>
                                                                                                                                                                                                                                 <dependency>
                                                                                                                                                                                                                                             <groupId>io.netty</groupId>
                                                                                                                                                                                                                                                         <artifactId>netty-all</artifactId>
                                                                                                                                                                                                                                                                     <version>4.1.52.Final</version>
                                                                                                                                                                                                                                                                             </dependency>
                                                                                                                                                                                                                                                                                 </dependencies>

                                                                                                                                                                                                                                                                                     <build>
                                                                                                                                                                                                                                                                                             <plugins>
                                                                                                                                                                                                                                                                                                         <plugin>
                                                                                                                                                                                                                                                                                                                         <groupId>org.springframework.boot</groupId>
                                                                                                                                                                                                                                                                                                                                         <artifactId>spring-boot-maven-plugin</artifactId>
                                                                                                                                                                                                                                                                                                                                                     </plugin>
                                                                                                                                                                                                                                                                                                                                                             </plugins>
                                                                                                                                                                                                                                                                                                                                                                 </build>

                                                                                                                                                                                                                                                                                                                                                                 </project>
                                                                                                                                                                                                                                                                                                                                                                 EOF

                                                                                                                                                                                                                                                                                                                                                                 # Create User.java file
                                                                                                                                                                                                                                                                                                                                                                 cat > p2p-chat-example/src/main/java/com/example/p2p/chat/model/User.java <<EOF
                                                                                                                                                                                                                                                                                                                                                                 package com.example.p2p.chat.model;

                                                                                                                                                                                                                                                                                                                                                                 import javax.persistence.Entity;
                                                                                                                                                                                                                                                                                                                                                                 import javax.persistence.Id;
                                                                                                                                                                                                                                                                                                                                                                 import javax.persistence.GeneratedValue;
                                                                                                                                                                                                                                                                                                                                                                 import javax.persistence.GenerationType;

                                                                                                                                                                                                                                                                                                                                                                 @Entity
                                                                                                                                                                                                                                                                                                                                                                 public class User {
                                                                                                                                                                                                                                                                                                                                                                        @Id
                                                                                                                                                                                                                                                                                                                                                                            @GeneratedValue(strategy = GenerationType.IDENTITY)
                                                                                                                                                                                                                                                                                                                                                                                private Long id;
                                                                                                                                                                                                                                                                                                                                                                                    private String username;
                                                                                                                                                                                                                                                                                                                                                                                        private String password;
                                                                                                                                                                                                                                                                                                                                                                                            private String publicKey;

                                                                                                                                                                                                                                                                                                                                                                                                // getters and setters
                                                                                                                                                                                                                                                                                                                                                                 }
                                                                                                                                                                                                                                                                                                                                                                 EOF

                                                                                                                                                                                                                                                                                                                                                                 # Create ChatMessage.java file
                                                                                                                                                                                                                                                                                                                                                                 cat > p2p-chat-example/src/main/java/com/example/p2p/chat/model/ChatMessage.java <<EOF
                                                                                                                                                                                                                                                                                                                                                                 package com.example.p2p.chat.model;

                                                                                                                                                                                                                                                                                                                                                                 import javax.persistence.Entity;
                                                                                                                                                                                                                                                                                                                                                                 import javax.persistence.Id;
                                                                                                                                                                                                                                                                                                                                                                 import javax.persistence\GeneratedValue;
                                                                                                                                                                                                                                                                                                                                                                 import javax.persistence.GenerationType;

                                                                                                                                                                                                                                                                                                                                                                 @Entity
                                                                                                                                                                                                                                                                                                                                                                 public class ChatMessage {
                                                                                                                                                                                                                                                                                                                                                                        @Id
                                                                                                                                                                                                                                                                                                                                                                            @GeneratedValue(strategy = GenerationType.IDENTITY)
                                                                                                                                                                                                                                                                                                                                                                                private Long id;
                                                                                                                                                                                                                                                                                                                                                                                    private String senderId;
                                                                                                                                                                                                                                                                                                                                                                                        private String recipientId;
                                                                                                                                                                                                                                                                                                                                                                                            private String message;

                                                                                                                                                                                                                                                                                                                                                                                                // getters and setters
                                                                                                                                                                                                                                                                                                                                                                 }
                                                                                                                                                                                                                                                                                                                                                                 EOF

                                                                                                                                                                                                                                                                                                                                                                 # Create UserService.java file
                                                                                                                                                                                                                                                                                                                                                                 cat > p2p-chat-example/src/main/java/com/example/p2p/chat/service/UserService.java <<EOF
                                                                                                                                                                                                                                                                                                                                                                 package com.example.p2p.chat.service;

                                                                                                                                                                                                                                                                                                                                                                 import com.example.p2p.chat.model.User;
                                                                                                                                                                                                                                                                                                                                                                 import com.example.p2p.chat.repository.UserRepository;

                                                                                                                                                                                                                                                                                                                                                                 import org.springframework.beans.factory.annotation.Autowired;
                                                                                                                                                                                                                                                                                                                                                                 import org.springframework.stereotype.Service;

                                                                                                                                                                                                                                                                                                                                                                 import java.util.List;

                                                                                                                                                                                                                                                                                                                                                                 @Service
                                                                                                                                                                                                                                                                                                                                                                 public class UserService {
                                                                                                                                                                                                                                                                                                                                                                        @Autowired
                                                                                                                                                                                                                                                                                                                                                                            private UserRepository userRepository;

                                                                                                                                                                                                                                                                                                                                                                                public User signup(User user) {
                                                                                                                                                                                                                                                                                                                                                                                            return userRepository.save(user);
                                                                                                                                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                                                                                                                                    public User login(String username, String password) {
                                                                                                                                                                                                                                                                                                                                                                                                return userRepository.findByUsernameAndPassword(username, password);
                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                 }
                                                                                                                                                                                                                                                                                                                                                                 EOF

                                                                                                                                                                                                                                                                                                                                                                 # Create ChatService.java file
                                                                                                                                                                                                                                                                                                                                                                 cat > p2p-chat-example/src/main/java/com/example/p2p/chat/service/ChatService.java <<EOF
                                                                                                                                                                                                                                                                                                                                                                 package com.example.p2p.chat.service;

                                                                                                                                                                                                                                                                                                                                                                 import com.example.p2p.chat.model.ChatMessage;
                                                                                                                                                                                                                                                                                                                                                                 import com.example.p2p.chat.repository.ChatMessageRepository;

                                                                                                                                                                                                                                                                                                                                                                 import org.springframework.beans.factory.annotation.Autowired;
                                                                                                                                                                                                                                                                                                                                                                 import org.springframework.stereotype.Service;

                                                                                                                                                                                                                                                                                                                                                                 import java.util.List;

                                                                                                                                                                                                                                                                                                                                                                 @Service
                                                                                                                                                                                                                                                                                                                                                                 public class ChatService {
                                                                                                                                                                                                                                                                                                                                                                        @Autowired
                                                                                                                                                                                                                                                                                                                                                                            private ChatMessageRepository chatMessageRepository;

                                                                                                                                                                                                                                                                                                                                                                                public void sendMessage(ChatMessage message) {
                                                                                                                                                                                                                                                                                                                                                                                            chatMessageRepository.save(message);
                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                 }
                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                 }
                                                                                                                                                                                                                                                                                                                                                                 }
                                                                                                                                                                                                                                                                                                                                                                 }